[workspace]
members = [
  "programs/social_draw",
  "programs/nfc_registry",
]
resolver = "2"

[workspace.dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }

[profile.release]
overflow-checks = true
